server:
  port: 8081
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/opdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
resilience4j:
  circuitbreaker:
    instances:
      orderServiceCB:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      inventory-service:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
  retry:
    instances:
      orderServiceRetry:
        maxAttempts: 3
        waitDuration: 500ms
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
