server:
  port: 8083
spring:
  application:
    name: notification-service
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/opdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
resilience4j:
  circuitbreaker:
    instances:
      orderServiceCB:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      orderServiceRetry:
        maxAttempts: 3
        waitDuration: 500ms
logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.orderpulse.notification: DEBUG
  file:
    name: logs/notification.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
