server:
  port: 8761
spring:
  application:
    name: discovery-server
  cloud:
    config:
        enabled: false
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
